notas = []
ginasta = input('qual o nome do ginasta: ')
for i in range(7):
    nota = float(input('qual a nota do jurado: '))
    notas.append(nota)
print(f'Primeira nota:          {notas[0]}m')
print(f'Segunda nota:          {notas[1]}m')
print(f'Terceira nota:          {notas[2]}m')
print(f'Quarta nota:          {notas[3]}m')
print(f'Quinta nota:          {notas[4]}m')
print(f'Sexta nota:          {notas[5]}m')
print(f'Setima nota:          {notas[6]}m')
print(f'resultado final: ')
print(f'Atleta:             {ginasta}')
print(f'melhor nota :            {max(notas)}m')
print(f'menor nota:            {min(notas)}m')
notas.remove(max(notas))
notas.remove(min(notas))
media = sum(notas) / len(notas)
print(f'media:            {media}m')
